version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  pytest:
    docker:
      # specify the version you desire here
      - image: cimg/python:3.9
        auth:
          username: $DOCKERHUB_USERNAME # context environment variable reference
          password: $DOCKERHUB_PASSWORD # context environment variable reference
    # 1vCPU & 2GB = small
    # 2vCPU & 4GB = medium
    resource_class: small
    steps:
      - checkout
      - run:
          name: install
          command: |
            pip install .[dev]
      - run:
          name: Run pre-commit checks again
          command: |
            pre-commit install
            pre-commit run --all-files
      - run:
          name: Run tests
          command: |
            mkdir -p server-test-reports/pytest
            # --cov --cov-report xml:server-test-reports/coverage.xml  = report test coverage to a file
            # --junitxml server-test-reports/pytest/tests.xml  = output also in XML to a file (for CircleCI to parse)
            pytest tests/ -s --cov --cov-report xml:server-test-reports/coverage.xml --junitxml server-test-reports/pytest/tests.xml --log-cli-level ERROR

      - store_test_results:
          # must be a directory with named subdirectories
          path: server-test-reports

      - codecov/upload

  dockerhub_publish:
    docker:
      # specify the version you desire here
      - image: cimg/python:3.9
        auth:
          username: $DOCKERHUB_USERNAME # context environment variable reference
          password: $DOCKERHUB_PASSWORD # context environment variable reference
    # 1vCPU & 2GB = small is too small for reference data
    # 2vCPU & 4GB = medium
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build Docker images
          command: |
            docker/build.sh
      - when:
          condition:
            equal: [main, << pipeline.git.branch >>]
          steps:
            - run:
                name: Push to Dockerhub latest
                command: |
                  docker logout
                  docker login --username sanogenetics --password $DOCKERHUB_PASSWORD
                  docker tag illumina2vcf:latest sanogenetics/illumina2vcf:latest
                  docker push sanogenetics/illumina2vcf:latest
                  docker tag illumina2vcf:latest-ref sanogenetics/illumina2vcf:latest-ref
                  docker push sanogenetics/illumina2vcf:latest-ref
                  docker tag illumina2vcf:latest-test-ref sanogenetics/illumina2vcf:latest-test-ref
                  docker push sanogenetics/illumina2vcf:latest-test-ref
                  docker logout
      - when:
          condition: << pipeline.git.tag >>
          steps:
            - run:
                name: Push to Dockerhub tag
                command: |
                  docker logout
                  docker login --username sanogenetics --password $DOCKERHUB_PASSWORD
                  docker tag illumina2vcf:latest sanogenetics/illumina2vcf:<< pipeline.git.tag >>
                  docker push sanogenetics/illumina2vcf:<< pipeline.git.tag >>
                  docker tag illumina2vcf:latest-ref sanogenetics/illumina2vcf:<< pipeline.git.tag >>-ref
                  docker push sanogenetics/illumina2vcf:<< pipeline.git.tag >>-ref
                  docker tag illumina2vcf:latest-test-ref sanogenetics/illumina2vcf:<< pipeline.git.tag >>-test-ref
                  docker push sanogenetics/illumina2vcf:<< pipeline.git.tag >>-test-ref
                  docker logout

workflows:
  tests:
    jobs:
      - pytest:
          context:
            - "docker_hub_creds"
      - dockerhub_publish:
          requires:
            - pytest
          filters:
            branches:
              only:
                - master
            tags:
              only: /^[1-9][0-9]*\.[0-9]+\.[0-9]+$/
