# use the image that already has the full reference downloaded
FROM illumina2vcf:latest-ref as ref
WORKDIR /app

# install subset of reference genome - ~3GB download and ~5MB kept
# chr1,2,10 for chromosome ordering and autosomal testing
# chrX,Y for sex chromosome and PAR testing
# chrM for mitochondial chromosome testing
# useful for downstream testing purposes
RUN samtools faidx ref/Homo_sapiens_assembly38.fasta -o ref/Homo_sapiens_assembly38.trim.fasta chr1:1-1000000 chr2:1-1000000 chr10:1-1000000 chrX:1-3000000 chrY:1-3000000 chrM
RUN samtools faidx ref/Homo_sapiens_assembly38.trim.fasta


# now copy the references into the final image
# do this to use docker layer caching to cache the downloaded reference information

FROM illumina2vcf:latest

WORKDIR /app
RUN mkdir ref

COPY --from=ref /app/ref/Homo_sapiens_assembly38.trim.fasta ref/Homo_sapiens_assembly38.fasta
COPY --from=ref /app/ref/Homo_sapiens_assembly38.trim.fasta.fai ref/Homo_sapiens_assembly38.fasta.fai

# install reference extras
COPY ref/GSAMD-24v3-0-EA_20034606_A2_blocklist.txt ref/
