# use base image that already has AWS CLI & HTSLIB+SAMTools+VCFTools
FROM sanogenetics/htslib-bcftools-samtools:latest as ref

WORKDIR /app

# install reference genome - ~3GB
# Docker ADD always downloads to verify cache
RUN mkdir ref
RUN curl "https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.fasta" \
  -o "ref/Homo_sapiens_assembly38.fasta"
RUN curl "https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.fasta.fai" \
  -o "ref/Homo_sapiens_assembly38.fasta.fai"

RUN curl "https://sano-public.s3.eu-west-2.amazonaws.com/GSA-24v3-0_A2.csv.gz" \
  -o ref/GSA-24v3-0_A2.csv.gz

# now copy the references into the final image
# do this to use docker layer caching to cache the downloaded reference information

FROM illumina2vcf:latest

WORKDIR /app
RUN mkdir ref

COPY --from=ref /app/ref/Homo_sapiens_assembly38.fasta ref/Homo_sapiens_assembly38.fasta
COPY --from=ref /app/ref/Homo_sapiens_assembly38.fasta.fai ref/Homo_sapiens_assembly38.fasta.fai

COPY --from=ref /app/ref/GSA-24v3-0_A2.csv.gz ref/GSA-24v3-0_A2.csv.gz

# install reference extras
COPY ref/GSAMD-24v3-0-EA_20034606_A2_blocklist.txt ref/
