# use base image that already has AWS CLI & HTSLIB+SAMTools+VCFTools
FROM sanogenetics/htslib-bcftools-samtools:1.15.1 as ref

WORKDIR /app

# install subset of reference genome - ~3GB download and ~500KB kept
# chr1,2,10 for chromosome ordering and autosomal testing
# chrX,Y for sex chromosome and PAR testing
# chrM for mitochondial chromosome testing
# useful for downstream testing purposes
# Docker ADD always downloads to verify cache
RUN mkdir ref
RUN apt-get install -y libssl-dev
RUN samtools faidx -o ref/Homo_sapiens_assembly38.fasta \
  'https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.fasta' \
  chr1:0-1000000 \
  chr2:0-1000000 \
  chr10:0-1000000 \
  chrX:0-3000000 \
  chrY:0-3000000 \
  chrM
RUN samtools faidx ref/Homo_sapiens_assembly38.fasta


# now copy the references into the final image
# do this to use docker layer caching to cache the downloaded reference information

FROM sanogenetics/illumina2vcf:latest

WORKDIR /app
RUN mkdir ref

COPY --from=ref /app/ref/Homo_sapiens_assembly38.fasta ref/Homo_sapiens_assembly38.fasta
COPY --from=ref /app/ref/Homo_sapiens_assembly38.fasta.fai ref/Homo_sapiens_assembly38.fasta.fai

# install reference extras
COPY ref/GSAMD-24v3-0-EA_20034606_A2_blocklist.txt ref/
